# Generated by Django 4.2.4 on 2023-08-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_key', models.CharField()),
                ('commence_time', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('team_1', models.CharField()),
                ('team_2', models.CharField()),
                ('spread_1', models.IntegerField()),
                ('spread_2', models.IntegerField()),
                ('score_1', models.IntegerField(default=0)),
                ('score_2', models.IntegerField(default=0)),
                ('winner', models.CharField(default='TBD')),
            ],
        ),
    ]
