# Generated by Django 4.2.4 on 2023-08-08 20:14

import bettor_app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bettor',
            name='username',
            field=models.CharField(unique=True, validators=[bettor_app.validators.validate_username, django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(12)]),
        ),
    ]
