# Generated by Django 4.2.3 on 2023-08-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField()),
                ('commence_time', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('home_team', models.CharField()),
                ('away_team', models.CharField()),
                ('home_team_spread', models.IntegerField()),
                ('away_team_spread', models.IntegerField()),
                ('home_team_score', models.IntegerField(default=0)),
                ('away_team_score', models.IntegerField(default=0)),
                ('bettor_pick', models.CharField(null=True)),
                ('winner', models.CharField(null=True)),
                ('bet_status', models.CharField(default='Pending')),
            ],
        ),
    ]
