# Generated by Django 4.2.4 on 2023-08-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='won',
        ),
        migrations.AddField(
            model_name='bet',
            name='status',
            field=models.CharField(default='Pending'),
        ),
    ]
