# Generated by Django 4.2.3 on 2023-08-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='away_team_spread',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='home_team_spread',
            field=models.IntegerField(null=True),
        ),
    ]
