# Generated by Django 4.2.3 on 2023-08-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet_app', '0003_alter_bet_away_team_spread_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='away_team_spread',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bet',
            name='home_team_spread',
            field=models.IntegerField(default=0),
        ),
    ]
